version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - nginx
    restart: always
    environment:
      DOMAINS: '0.0.0.0 -> http://nginx:8000'
      STAGE: production
      # FORCE_RENEW: 'true'
    volumes:
      - ./ssl-certs:/var/lib/https-portal

  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html
    depends_on:
      - php

  php:
    image: php:7-fpm
    build: ./php/
    volumes:
      - ./web:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - sql

  sql:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/database:/var/lib/mysql
      - ./data/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: User
      MYSQL_USER: root
      MYSQL_PASSWORD: password # replace password with yours
      TZ: 'Asia/Tokyo'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=sql
      - PMA_USER=root
      - PMA_PASSWORD=password # replace password with yours
    depends_on:
      - sql
    volumes:
      - /sessions
      - ./phpmyadmin/config.inc.php:/var/www/html/config.inc.php

